version: 2
jobs:
  build:
    docker:
      - image: node:10
    working_directory: ~/website
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run: yarn install
      - run: yarn lint
      - save_cache:
          paths:
            - ~/website/node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
